### PR TITLE
Fix C_ATTRIBUTE.isleaf(), fixes #241

### LINKED ISSUE #241: Possible problem in CAttribute -> isLeaf()
I think it is just doing the oppositie thing one expects.

Anyway, I don't see how an attribute can be a leaf, but if the method is there it should work as expected.

Or do I misunderstand the concept of CAttribute?

Thanks for any comment.

### PR DESCRIPTION
**Pull request by pieterbos**
In #241 , Bert Verhees found that CAttribute.isLeaf() did the exact opposite of what it should do. This fixes it.

### CODE REVIEW

File: aom/src/main/java/com/nedap/archie/aom/CAttribute.java [hunk 1]
```diff
@@ -372,7 +372,7 @@ public boolean isProhibited() {
     @Override
     @JsonIgnore
     public boolean isLeaf() {
-        return children != null && children.size() > 0;
+        return children == null || children.isEmpty();
```
Comment (J3173) [inline aom/src/main/java/com/nedap/archie/aom/CAttribute.java:375]: It look like `children` can't be null. `setChildren(null)` will make it an empty list.

**Review by J3173 — APPROVED** [review]

File: aom/src/main/java/com/nedap/archie/aom/CAttribute.java (hunk 1 above)
Comment (pieterbos) [reply aom/src/main/java/com/nedap/archie/aom/CAttribute.java:375]: Correct. However, I'd like to keep this null check, just to be sure and to prevent problems after future code changes. We don't have compile time Kotlin style null checks, and these methods should always just work.

File: tools/src/test/java/com/nedap/archie/aom/CComplexObjectProxyTest.java [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+import static org.junit.Assert.*;
+
+public class CComplexObjectProxyTest {
+
+    @Test
+    public void isLeaf() {
+        CComplexObject cComplexObject = new CComplexObject();
+
+        assertTrue(cComplexObject.isLeaf());
```
Comment (pieterbos) [inline tools/src/test/java/com/nedap/archie/aom/CComplexObjectProxyTest.java:13]: In operational templates, I think these can contain child nodes. Same with Archetype slots. I'll check later, and fix both implementation and test. Unless Jelte wants to do this? :)

Comment (J3173) [reply tools/src/test/java/com/nedap/archie/aom/CComplexObjectProxyTest.java:13]: > Unless Jelte wants to do this? :)
No, not now.

Comment (pieterbos) [reply tools/src/test/java/com/nedap/archie/aom/CComplexObjectProxyTest.java:13]: I checked this, and they can definately not contain children. So this test plus implementation is correct. Archetype roots actually can, but those are CComplexObjects and not tested separately. So I'm merging this PR :)
