### PR TITLE
Fix slot filling validation, fixes #242

### LINKED ISSUE #242: Slot filling in validation is too strict
Code: 
https://github.com/openEHR/archie/blob/985e1318546742d022905b9ac778e61190373c82/aom/src/main/java/com/nedap/archie/aom/utils/AOMUtils.java#L203

Specification says: 'only validate includes if an open excludes is present'
Code does: always validate includes.

So fix, perhaps in the same way as https://github.com/openEHR/adl-tools/blob/83171f135b4c12836d7e09b0c0a6770a47585a93/components/adl_compiler/src/validator/aom_validator.e#L86-L126

### PR DESCRIPTION
**Pull request by pieterbos**
Fixes #242 and #244

Note that archetype slots with a substantive includes or excludes, the other being not present, is a recommendation. We may need another method to get recommendations, for tooling purposes, and one to check if the slot is a recommendation. This however, will be a future issue, this PR is just to get the conversion and validation right.

# Validation changes

This implements the spec as in https://specifications.openehr.org/releases/AM/latest/ADL2.html#_formal_semantics_of_include_and_exclude_constraints , which means:
- slot includes or excludes can have one of these three constraints:
  - it can be open, having an open includes/excludes, meaning `archetype_id/value matches {/.*}`
  - it can be substantive, having actual constraints
  - it can not have includes or excludes at all.

- A slot with only an excludes, or only includes, is recommendation, not a formal binding
- A slot with one open and one substantive binding, is formally binding

So this PR just checks it if it's formally binding.

# conversion changes

Archetype ID are different in ADL 1.4 and ADL 2. In ADL 2, they have full version information. Since in the ADL 2 spec, this archetype id patterns in slots are a pure lexical operation against the entire id, archetype slots in ADL 1.4 need a conversion step to be valid in ADL 2: every time a .v1 or .v0 or .v5 is used, a suffix needs to be appended. This PR adds that suffix.

- [x] Create separate issue for the new methods: #246

### CODE REVIEW

File: aom/src/main/java/com/nedap/archie/aom/utils/AOMUtils.java [hunk 1]
```diff
@@ -197,39 +197,42 @@ public static boolean codeExistsAtLevel(String nodeId, int specializationDepth)
...
+            return false;
+        } else if (!isSlotPresentAndOpen(slot.getExcludes()) && isSlotPresentAndOpen(slot.getIncludes())) {
+            for (Assertion exclude : slot.getExcludes()) {
+                if (matchesExclude(exclude.getExpression(), archetypeRef)) {
+                    return false;
                 }
             }
         }
-        return includePasses;
+        return true;
```
Comment (VeraPrinsen) [inline aom/src/main/java/com/nedap/archie/aom/utils/AOMUtils.java:215]: If both the include and exclude at this point are present but not open (which is not allowed), is that at this point already validated or does this method just assume that will never be the case?

**Review by VeraPrinsen — APPROVED** [review]
Just one question about an edge case

File: aom/src/main/java/com/nedap/archie/aom/utils/AOMUtils.java (hunk 1 above)
Comment (pieterbos) [reply aom/src/main/java/com/nedap/archie/aom/utils/AOMUtils.java:215]: This will result in the archetype not validating. See [this example](https://github.com/openehr/archie/blob/master/tools/src/test/resources/adl2-tests/validity/slots/openEHR-EHR-SECTION.VDSEV_slot_include_not_any_exclude_not_any.v1.0.0.adls) for a test case that runs as part of the BigArchetypeValidator, and see VariousStructureValidation.java for the implementation of the `VDSEV`-validation.

So, this situation could still happen, but does not mean anything. In that case, there's the choice of here returning true or false, or throwing an exception. The exception seemed like a not so good idea - you don't want this method to fail and mess up whatever you were doing. Returning false also seems like a less good idea - it prevents people from working with these archetypes. So returning true was the choice I made.

Comment (VeraPrinsen) [reply aom/src/main/java/com/nedap/archie/aom/utils/AOMUtils.java:215]: Ok!

**Review by MattijsK — APPROVED** [review]
Awesome tests!
